import React, { useMemo, useState } from 'react';
import { ArrowUpRight, CalendarDays, Check, CheckCircle2, Circle, Compass, Filter, Flag, Pencil, Plus, Search, Sparkles, Trash2, X } from 'lucide-react';
import { LifeMilestone } from '../types';
import { Sound } from '../utils/audio';
import { triggerConfetti } from '../utils/confetti';

interface LifeTimelineProps { milestones: LifeMilestone[]; onAddMilestone: (item: Omit<LifeMilestone, 'id'>) => void; onUpdateMilestone?: (id: string, updated: Partial<LifeMilestone>) => void; onDeleteMilestone: (id: string) => void; soundEnabled: boolean; }
const categoryColors: Record<string, string> = { Career: '#7c3aed', Project: '#2563eb', Education: '#0f766e', Health: '#db2777', Personal: '#d97706', Travel: '#0891b2', Life: '#65a30d' };
const getColor = (category: string) => categoryColors[category] || '#64748b';
const formatDate = (value: string, year: number) => { const date = new Date(`${value || `${year}-01-01`}T00:00:00`); return Number.isNaN(date.getTime()) ? String(year) : date.toLocaleDateString([], { month: 'short', day: 'numeric', year: 'numeric' }); };
const emptyForm = () => ({ title: '', year: String(new Date().getFullYear()), dateStr: new Date().toISOString().slice(0, 10), description: '', category: 'Career', status: 'in_progress' as LifeMilestone['status'], progress: 50, icon: '✦', relatedProject: '' });

export const LifeTimeline: React.FC<LifeTimelineProps> = ({ milestones, onAddMilestone, onUpdateMilestone, onDeleteMilestone, soundEnabled }) => {
  const [query, setQuery] = useState('');
  const [category, setCategory] = useState('All');
  const [status, setStatus] = useState<'All' | 'completed' | 'in_progress' | 'upcoming'>('All');
  const [selectedId, setSelectedId] = useState<string | null>(milestones[0]?.id || null);
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [editingId, setEditingId] = useState<string | null>(null);
  const [form, setForm] = useState(emptyForm);
  const categories = useMemo(() => ['All', ...Array.from(new Set(milestones.map((item) => item.category))).sort()], [milestones]);
  const filtered = useMemo(() => milestones.filter((item) => category === 'All' || item.category === category).filter((item) => status === 'All' || (item.status || 'upcoming') === status).filter((item) => `${item.title} ${item.description} ${item.category}`.toLowerCase().includes(query.toLowerCase().trim())).sort((a, b) => (a.dateStr || `${a.year}-01-01`).localeCompare(b.dateStr || `${b.year}-01-01`)), [milestones, category, status, query]);
  const selected = milestones.find((item) => item.id === selectedId) || filtered[filtered.length - 1] || milestones[milestones.length - 1];
  const completed = milestones.filter((item) => item.status === 'completed').length;
  const active = milestones.filter((item) => item.status === 'in_progress').length;
  const progress = milestones.length ? Math.round(milestones.reduce((sum, item) => sum + (item.progress ?? (item.status === 'completed' ? 100 : 0)), 0) / milestones.length) : 0;
  const openCreate = () => { setEditingId(null); setForm(emptyForm()); setIsModalOpen(true); };
  const openEdit = (item: LifeMilestone) => { setEditingId(item.id); setForm({ title: item.title, year: String(item.year), dateStr: item.dateStr, description: item.description, category: item.category, status: item.status || 'upcoming', progress: item.progress ?? 0, icon: item.icon || '✦', relatedProject: item.relatedProject || '' }); setIsModalOpen(true); };
  const save = (event: React.FormEvent) => { event.preventDefault(); if (!form.title.trim()) return; const payload = { title: form.title.trim(), year: Number(form.year) || new Date().getFullYear(), dateStr: form.dateStr, description: form.description.trim(), category: form.category, status: form.status, progress: Number(form.progress), icon: form.icon || '✦', relatedProject: form.relatedProject.trim() || undefined }; if (editingId && onUpdateMilestone) onUpdateMilestone(editingId, payload); else { onAddMilestone(payload); triggerConfetti(); } Sound.success(soundEnabled); setIsModalOpen(false); };
  const toggle = (item: LifeMilestone) => { if (!onUpdateMilestone) return; const nextCompleted = item.status !== 'completed'; onUpdateMilestone(item.id, { status: nextCompleted ? 'completed' : 'in_progress', progress: nextCompleted ? 100 : Math.min(item.progress ?? 50, 90) }); if (nextCompleted) triggerConfetti(); Sound.click(soundEnabled); };

  return <div className="lifemap-page">
    <section className="lifemap-hero"><div><div className="lifemap-kicker"><Compass size={14} /> YOUR LIFE, IN MOTION</div><h1 className="workspace-heading text-gray-900 dark:text-white">LifeMap</h1><p>Turn scattered chapters into a clear path forward. Capture what happened, what matters now, and where you want to go next.</p></div><div className="lifemap-hero-orbit"><span /><span /><span /><Sparkles size={22} /></div><button type="button" className="lifemap-primary" onClick={openCreate}><Plus size={16} /> Add milestone</button></section>
    <section className="lifemap-stats"><div><span className="stat-dot violet"><Flag size={14} /></span><small>Milestones</small><strong>{milestones.length}</strong><em>your chapters</em></div><div><span className="stat-dot mint"><CheckCircle2 size={14} /></span><small>Completed</small><strong>{completed}</strong><em>{milestones.length ? Math.round((completed / milestones.length) * 100) : 0}% of map</em></div><div><span className="stat-dot amber"><Sparkles size={14} /></span><small>In progress</small><strong>{active}</strong><em>keep the momentum</em></div><div><span className="stat-dot blue"><ArrowUpRight size={14} /></span><small>Journey health</small><strong>{progress}%</strong><em>average progress</em></div></section>
    <section className="lifemap-toolbar"><div className="lifemap-search"><Search size={15} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search your chapters..." /></div><div className="lifemap-filters"><Filter size={14} />{categories.map((item) => <button type="button" key={item} className={category === item ? 'active' : ''} onClick={() => setCategory(item)}>{item}</button>)}</div><select value={status} onChange={(event) => setStatus(event.target.value as typeof status)} aria-label="Filter by status"><option value="All">All statuses</option><option value="completed">Completed</option><option value="in_progress">In progress</option><option value="upcoming">Upcoming</option></select></section>
    <section className="lifemap-workspace"><div className="lifemap-rail"><div className="rail-line" />{filtered.length === 0 ? <div className="lifemap-empty"><Compass size={26} /><b>{milestones.length ? 'No chapters match this filter' : 'Your map starts here'}</b><span>{milestones.length ? 'Try another search or category.' : 'Add a milestone to begin shaping your story.'}</span><button type="button" onClick={openCreate}><Plus size={14} /> Add first milestone</button></div> : filtered.map((item) => { const color = getColor(item.category); return <button type="button" key={item.id} className={`lifemap-node ${selected?.id === item.id ? 'selected' : ''}`} onClick={() => setSelectedId(item.id)} style={{ '--node-color': color } as React.CSSProperties}><span className="node-marker">{item.status === 'completed' ? <Check size={14} /> : item.icon || <Circle size={12} />}</span><span className="node-copy"><small>{formatDate(item.dateStr, item.year)} · {item.category}</small><strong>{item.title}</strong><span>{item.status === 'completed' ? 'Completed' : item.status === 'in_progress' ? `${item.progress ?? 0}% in progress` : 'Up next'}</span></span></button>; })}</div><aside className="lifemap-inspector">{selected ? <><div className="inspector-top"><span className="inspector-icon" style={{ background: `${getColor(selected.category)}18`, color: getColor(selected.category) }}>{selected.icon || '✦'}</span><div><small>{selected.category} · {formatDate(selected.dateStr, selected.year)}</small><h2>{selected.title}</h2></div><button type="button" onClick={() => openEdit(selected)} title="Edit milestone"><Pencil size={15} /></button></div><p className="inspector-description">{selected.description || 'Add a reflection to remember why this chapter matters.'}</p><div className="inspector-progress"><div><span>Progress</span><b>{selected.progress ?? (selected.status === 'completed' ? 100 : 0)}%</b></div><div className="progress-track"><span style={{ width: `${selected.progress ?? (selected.status === 'completed' ? 100 : 0)}%`, background: getColor(selected.category) }} /></div></div><div className="inspector-meta"><span><CalendarDays size={14} /> {selected.targetDate || formatDate(selected.dateStr, selected.year)}</span>{selected.relatedProject && <span><Sparkles size={14} /> {selected.relatedProject}</span>}</div><div className="inspector-actions"><button type="button" onClick={() => toggle(selected)}><CheckCircle2 size={15} /> {selected.status === 'completed' ? 'Mark in progress' : 'Mark complete'}</button><button type="button" className="danger" onClick={() => { onDeleteMilestone(selected.id); setSelectedId(null); }}><Trash2 size={15} /></button></div></> : <div className="inspector-placeholder"><Compass size={34} /><b>Select a chapter</b><span>Choose a point on your map to see the details.</span></div>}</aside></section>
    {isModalOpen && <div className="lifemap-modal-backdrop" role="presentation"><form className="lifemap-modal" onSubmit={save}><div className="modal-head"><div><small>{editingId ? 'REFINE THIS CHAPTER' : 'ADD TO YOUR MAP'}</small><h2>{editingId ? 'Edit milestone' : 'New milestone'}</h2></div><button type="button" onClick={() => setIsModalOpen(false)} aria-label="Close"><X size={18} /></button></div><label>Title<input required value={form.title} onChange={(event) => setForm({ ...form, title: event.target.value })} placeholder="e.g. Launch my portfolio" /></label><div className="modal-grid"><label>Date<input type="date" value={form.dateStr} onChange={(event) => setForm({ ...form, dateStr: event.target.value, year: event.target.value.slice(0, 4) })} /></label><label>Category<select value={form.category} onChange={(event) => setForm({ ...form, category: event.target.value })}>{['Career', 'Project', 'Education', 'Health', 'Personal', 'Travel', 'Life'].map((item) => <option key={item}>{item}</option>)}</select></label></div><label>Reflection<textarea rows={3} value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} placeholder="What makes this chapter meaningful?" /></label><div className="modal-grid"><label>Status<select value={form.status} onChange={(event) => setForm({ ...form, status: event.target.value as LifeMilestone['status'] })}><option value="upcoming">Upcoming</option><option value="in_progress">In progress</option><option value="completed">Completed</option></select></label><label>Progress<input type="number" min="0" max="100" value={form.progress} onChange={(event) => setForm({ ...form, progress: Number(event.target.value) })} /></label></div><label>Icon<input maxLength={2} value={form.icon} onChange={(event) => setForm({ ...form, icon: event.target.value })} /></label><button className="lifemap-primary modal-submit" type="submit"><Check size={16} /> Save milestone</button></form></div>}
  </div>;
};
